source/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('bdd/admin/', admin.site.urls),
    path('', include('sources.urls')),
]

sources/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('', views.dashboard, name='dashboard'),
    path('create/', views.create_group, name='create_group'),
    path('submit/', views.submit_group, name='submit_group'),
    
    path('integrante', views.integrante, name='integrante'),
    path('administrador', views.administrador, name='administrador'),

    # Rotas para Usuario
    path('usuarios/', views.usuario_list, name='usuario_list'),
    path('usuarios/create/', views.usuario_create, name='usuario_create'),
    path('usuarios/<int:pk>/update/', views.usuario_update, name='usuario_update'),
    path('usuarios/<int:pk>/delete/', views.usuario_delete, name='usuario_delete'),

    # Rotas para Administrador
    path('administradores/', views.administrador_list, name='administrador_list'),
    path('administradores/create/', views.administrador_create, name='administrador_create'),
    path('administradores/<int:pk>/update/', views.administrador_update, name='administrador_update'),
    path('administradores/<int:pk>/delete/', views.administrador_delete, name='administrador_delete'),

    # Rotas para Grupo
    path('grupos/', views.grupo_list, name='grupo_list'),
    path('grupos/create/', views.grupo_create, name='grupo_create'),
    path('grupos/<int:pk>/update/', views.grupo_update, name='grupo_update'),
    path('grupos/<int:pk>/delete/', views.grupo_delete, name='grupo_delete'),

    # Rotas para Subgrupo
    path('subgrupos/', views.subgrupo_list, name='subgrupo_list'),
    path('subgrupos/create/', views.subgrupo_create, name='subgrupo_create'),
    path('subgrupos/<int:pk>/update/', views.subgrupo_update, name='subgrupo_update'),
    path('subgrupos/<int:pk>/delete/', views.subgrupo_delete, name='subgrupo_delete'),

    # Rotas para Tarefa
    path('tarefas/', views.tarefa_list, name='tarefa_list'),
    path('tarefas/create/', views.tarefa_create, name='tarefa_create'),
    path('tarefas/<int:pk>/update/', views.tarefa_update, name='tarefa_update'),
    path('tarefas/<int:pk>/delete/', views.tarefa_delete, name='tarefa_delete'),

    # Rotas para Avaliacao
    path('avaliacoes/', views.avaliacao_list, name='avaliacao_list'),
    path('avaliacoes/create/', views.avaliacao_create, name='avaliacao_create'),
    path('avaliacoes/<int:pk>/update/', views.avaliacao_update, name='avaliacao_update'),
    path('avaliacoes/<int:pk>/delete/', views.avaliacao_delete, name='avaliacao_delete'),
]

sources/models.py
from django.db import models

class Usuario(models.Model):
    nome = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=255)

    def __str__(self):
        return self.nome

class Administrador(models.Model):
    user = models.OneToOneField(Usuario, on_delete=models.CASCADE)

    def __str__(self):
        return f'Admin: {self.user.nome}'

class Grupo(models.Model):
    admin = models.ForeignKey(Administrador, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255)
    limit_subgrupo_membro = models.IntegerField()
    limit_subgrupo = models.IntegerField()
    convite_link = models.URLField()

    def __str__(self):
        return self.nome

class Subgrupo(models.Model):
    representante = models.ForeignKey('Integrante', on_delete=models.SET_NULL, null=True)
    grupo = models.ManyToManyField(Grupo, through='SubgrupoGrupo')

    def __str__(self):
        return f'Subgrupo {self.id}'

class SubgrupoGrupo(models.Model):
    subgrupo = models.ForeignKey(Subgrupo, on_delete=models.CASCADE)
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)

class Integrante(models.Model):
    user = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    matricula = models.CharField(max_length=255)

    def __str__(self):
        return self.user.nome

class IntegranteGrupo(models.Model):
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)
    integrante = models.ForeignKey(Integrante, on_delete=models.CASCADE)

class IntegranteSubgrupo(models.Model):
    subgrupo = models.ForeignKey(Subgrupo, on_delete=models.CASCADE)
    integrante = models.ForeignKey(Integrante, on_delete=models.CASCADE)

class Solicita(models.Model):
    integrante = models.ForeignKey(Integrante, on_delete=models.CASCADE)
    subgrupo = models.ForeignKey(Subgrupo, on_delete=models.CASCADE)
    status = models.CharField(max_length=50)

class Tarefa(models.Model):
    grupo = models.ForeignKey(Grupo, on_delete=models.CASCADE)
    admin = models.ForeignKey(Administrador, on_delete=models.CASCADE)
    data_entrega = models.DateField()
    descricao = models.TextField()

    def __str__(self):
        return f'Tarefa {self.id}'

class Avaliacao(models.Model):
    tarefa = models.ForeignKey(Tarefa, on_delete=models.CASCADE)
    subgrupo = models.ForeignKey(Subgrupo, on_delete=models.CASCADE)
    entrega = models.DateField()
    participacao = models.TextField()
    nota = models.DecimalField(max_digits=5, decimal_places=2)
    arquivo = models.FileField(upload_to='avaliacoes/')

    def __str__(self):
        return f'Avaliacao {self.id} - Tarefa {self.tarefa.id}'

sources/forms.py
from django import forms

class TarefaForm(forms.Form):
    descricao = forms.CharField(label='Descrição da Tarefa', max_length=200)
    data_entrega = forms.DateField(label='Data de Entrega')

sources/views.py
# sources/views.py
from .forms import TarefaForm
from django.shortcuts import render, get_object_or_404, redirect
from .models import Usuario, Administrador, Grupo, Subgrupo, Tarefa, Avaliacao, Integrante
from django.http import HttpResponse

# Views existentes
def index(request):
    allGrupos = Grupo.objects.all()
    integrantes = Integrante.objects.all()
    tarefas = Tarefa.objects.all()
    representante = Administrador.objects.all()
    print(f"Grupos: ${integrantes[0]}, Integrantes: ${integrantes.count()}, Tarefas: ${tarefas}, Representante ${representante}")
    grupo1 = {
        'groups_data': [
            {
                'nome':integrantes[0],
                'integrantes': integrantes,
                'tarefas':tarefas.count(),
                'representante': representante
            }
        ]
    }
    grupoo1 = {
        'groups_data': [
            {'nome': 'Marcos', 'integrantes': 5, 'tarefas': 10, 'representante': {'nome': 'Rosa'},
            'integrantes': [
                {'nome': 'Rosa'}
            ]},
            {'nome': 'Felipe', 'integrantes': 3, 'tarefas': 8},
            {'nome': 'Jessica', 'integrantes': 7, 'tarefas': 15},
        ],

        'integrantes': [
            {'nome': 'João', 'tem_subgrupo': True},
            {'nome': 'Maria', 'tem_subgrupo': False},
            {'nome': 'Pedro', 'tem_subgrupo': True},
            {'nome': 'João', 'tem_subgrupo': False},
            {'nome': 'Maria', 'tem_subgrupo': False},
            {'nome': 'Pedro', 'tem_subgrupo': False},
            {'nome': 'João', 'tem_subgrupo': False},
            {'nome': 'Maria', 'tem_subgrupo': False},
            {'nome': 'Pedro', 'tem_subgrupo': True},
        ],

        'tarefas': [
            {'descricao': 'Fazer uma aplicação mobile', 'data_entrega': '01/07/2024'}
        ]
    }

    grupo2 = {
        'groups_data': [
            {'nome': 'Ana', 'integrantes': 6, 'tarefas': 12, 'representante': {'nome': 'Carlos'},
            'integrantes': [
                {'nome': 'Carlos'}
            ]},
            {'nome': 'Lucas', 'integrantes': 4, 'tarefas': 7},
            {'nome': 'Sofia', 'integrantes': 8, 'tarefas': 20},
        ],

        'integrantes': [
            {'nome': 'Paulo', 'tem_subgrupo': True},
            {'nome': 'Camila', 'tem_subgrupo': False},
            {'nome': 'Ricardo', 'tem_subgrupo': True},
            {'nome': 'Julia', 'tem_subgrupo': False},
            {'nome': 'Fernanda', 'tem_subgrupo': False},
            {'nome': 'Mateus', 'tem_subgrupo': False},
            {'nome': 'Andre', 'tem_subgrupo': False},
            {'nome': 'Mariana', 'tem_subgrupo': False},
            {'nome': 'Beatriz', 'tem_subgrupo': True},
        ],

        'tarefas': [
            {'descricao': 'Desenvolver um site', 'data_entrega': '10/07/2024'}
        ]
    }

    subgrupo = {'nome': 'Marcos', 'integrantes': 5, 'tarefas': 10, 'representante': {'nome': 'Rosa'},
            'integrantes': [
                {'nome': 'Marcos'}
            ]}

    view_param = request.GET.get('view', None)
    selected_group = request.GET.get('group', 'grupo1')

    grupo = grupo1 if selected_group == 'grupo1' else grupo2

    return render(request, 'index.html', {
        'view': view_param,
        'grupo': grupo,
        'subgrupo': subgrupo,
        'selected_group': selected_group
    })


def dashboard(request):
    view_param = request.GET.get('view', None)
    return render(request, 'index.html', {'view': view_param})


def criar_tarefa(request):
    if request.method == 'POST':
        form = TarefaForm(request.POST)
        if form.is_valid():
            # Processar os dados do formulário
            descricao = form.cleaned_data['descricao']
            data_entrega = form.cleaned_data['data_entrega']
            # Salvar os dados no banco de dados ou em outro sistema de armazenamento
            # Redirecionar para a página de visualização de todas as tarefas ou outra página de destino
            return redirect('todas_tarefas')
    else:
        form = TarefaForm()
    
    return render(request, 'console/criar_tarefa.html', {'form': form})

def submit_group(request):
    if request.method == 'POST':
        groupName = request.POST.get('groupName')
        numSubgroups = request.POST.get('numSubgroups')
        maxLimit = request.POST.get('maxLimit')

        return HttpResponse('Grupo criado com sucesso!')
    else:
        return HttpResponse('Método não permitido!')

def create_group(request):
    return render(request, 'create_group.html')


def integrante(request):
    return render(request, 'pages/integrante.html')

def administrador(request):
    return render(request, 'pages/administrador.html')

# Views para Usuario
def usuario_list(request):
    usuarios = Usuario.objects.all()
    return render(request, 'pages/usuario_list.html', {'usuarios': usuarios})

def usuario_create(request):
    if request.method == 'POST':
        # handle form submission
        pass
    return render(request, 'pages/usuario_form.html')

def usuario_update(request, pk):
    usuario = get_object_or_404(Usuario, pk=pk)
    if request.method == 'POST':
        # handle form submission
        pass
    return render(request, 'pages/usuario_form.html', {'usuario': usuario})

def usuario_delete(request, pk):
    usuario = get_object_or_404(Usuario, pk=pk)
    if request.method == 'POST':
        usuario.delete()
        return redirect('usuario_list')
    return render(request, 'pages/usuario_confirm_delete.html', {'usuario': usuario})

# Views para Administrador
def administrador_list(request):
    administradores = Administrador.objects.all()
    return render(request, 'pages/administrador_list.html', {'administradores': administradores})

def administrador_create(request):
    if request.method == 'POST':
        # handle form submission
        pass
    return render(request, 'pages/administrador_form.html')

def administrador_update(request, pk):
    administrador = get_object_or_404(Administrador, pk=pk)
    if request.method == 'POST':
        # handle form submission
        pass
    return render(request, 'pages/administrador_form.html', {'administrador': administrador})

def administrador_delete(request, pk):
    administrador = get_object_or_404(Administrador, pk=pk)
    if request.method == 'POST':
        administrador.delete()
        return redirect('administrador_list')
    return render(request, 'pages/administrador_confirm_delete.html', {'administrador': administrador})

# Similar views for Grupo, Subgrupo, Tarefa, Avaliacao

# Views para Grupo
def grupo_list(request):
    grupo = Grupo.objects.all()
    return render(request, 'pages/grupo_list.html', {'grupos': grupo})

def grupo_create(request):
    if request.method == 'POST':
        # handle form submission
        pass
    return render(request, 'pages/grupo_form.html')

def grupo_update(request, pk):
    grupo = get_object_or_404(Grupo, pk=pk)
    if request.method == 'POST':
        # handle form submission
        pass
    return render(request, 'pages/grupo_form.html', {'grupos': grupo})

def grupo_delete(request, pk):
    grupo = get_object_or_404(Grupo, pk=pk)
    if request.method == 'POST':
        grupo.delete()
        return redirect('grupo_list')
    return render(request, 'pages/grupo_confirm_delete.html', {'grupos': grupo})


# Views para Subgrupo
def subgrupo_list(request):
    subgrupo = Subgrupo.objects.all()
    return render(request, 'pages/subgrupo_list.html', {'subgrupos': subgrupo})

def subgrupo_create(request):
    if request.method == 'POST':
        # handle form submission
        pass
    return render(request, 'pages/subgrupo_form.html')

def subgrupo_update(request, pk):
    subgrupo = get_object_or_404(Subgrupo, pk=pk)
    if request.method == 'POST':
        # handle form submission
        pass
    return render(request, 'pages/subgrupo_form.html', {'subgrupos': subgrupo})

def subgrupo_delete(request, pk):
    subgrupo = get_object_or_404(Subgrupo, pk=pk)
    if request.method == 'POST':
        subgrupo.delete()
        return redirect('subgrupo_list')
    return render(request, 'pages/subgrupo_confirm_delete.html', {'subgrupos': subgrupo})


# Views para Tarefa
def tarefa_list(request):
    tarefa = Tarefa.objects.all()
    return render(request, 'pages/tarefa_list.html', {'tarefas': tarefa})

def tarefa_create(request):
    if request.method == 'POST':
        # handle form submission
        pass
    return render(request, 'pages/tarefa_form.html')

def tarefa_update(request, pk):
    tarefa = get_object_or_404(Tarefa, pk=pk)
    if request.method == 'POST':
        # handle form submission
        pass
    return render(request, 'pages/tarefa_form.html', {'grupos': tarefa})

def tarefa_delete(request, pk):
    tarefa = get_object_or_404(Tarefa, pk=pk)
    if request.method == 'POST':
        tarefa.delete()
        return redirect('tarefa_list')
    return render(request, 'pages/tarefa_confirm_delete.html', {'grupos': tarefa})


# Views para Avaliacao
def avaliacao_list(request):
    avaliacao = Avaliacao.objects.all()
    return render(request, 'pages/avaliacao_list.html', {'Avaliações': avaliacao})

def avaliacao_create(request):
    if request.method == 'POST':
        # handle form submission
        pass
    return render(request, 'pages/avaliacao_form.html')

def avaliacao_update(request, pk):
    avaliacao = get_object_or_404(Avaliacao, pk=pk)
    if request.method == 'POST':
        # handle form submission
        pass
    return render(request, 'pages/avaliacao_form.html', {'Avaliações': avaliacao})

def avaliacao_delete(request, pk):
    avaliacao = get_object_or_404(Avaliacao, pk=pk)
    if request.method == 'POST':
        avaliacao_list.delete()
        return redirect('avaliacao_list')
    return render(request, 'pages/avaliacao_confirm_delete.html', {'Avaliações': avaliacao})

sources/templates/all_task.html
<h2>Todas as Tarefas</h2>
<table>
    <thead>
        <tr>
            <th>Descrição</th>
            <th>Data de Entrega</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for tarefa in grupo.tarefas %}
        <tr>
            <td>{{ tarefa.descricao }}</td>
            <td>{{ tarefa.data_entrega }}</td>
            <td><a href="?view=taskDetail&task_id={{ task.id }}">Ver Detalhes</a></td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="2">Nenhuma tarefa encontrada.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

sources/templates/create_group.html
<div id="createGroupForm">
    <h2>Criar Novo Grupo</h2>
    <form action="{% url 'submit_group' %}" method="post">
        {% csrf_token %}
        <label for="groupName">Nome:</label>
        <input type="text" id="groupName" name="groupName"><br><br>
        <label for="numSubgroups">Quantidade de Subgrupos:</label>
        <input type="number" id="numSubgroups" name="numSubgroups"><br><br>
        <label for="maxLimit">Limite Máximo por Subgrupo:</label>
        <input type="number" id="maxLimit" name="maxLimit"><br><br>
        <button type="submit">Criar</button>
    </form>
</div>

sources/templates/create_subgroup.html
<h2>Integrantes do Grupo</h2>
<table>
    <thead>
        <tr>
            <th>Nome</th>
            <th>Status</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        {% for integrante in grupo.integrantes %}
        <tr>
            <td>{{ integrante.nome }}</td>
            <td>{% if integrante.tem_subgrupo %}
                    Com Subgrupo
                {% else %}
                    Sem Subgrupo
                {% endif %}
            </td>
            <td>
                {% if not integrante.tem_subgrupo %}
                <button onclick="enviarSolicitacao('{{ integrante.nome }}')">Enviar Solicitação</button>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

sources/templates/criar_tarefa.html
<h2>Criar Nova Tarefa</h2>
<form method="post">
    {% csrf_token %}
    <label for="id_descricao">Descrição da Tarefa:</label><br>
    <textarea id="id_descricao" name="descricao" maxlength="200" required style="width: 100%;" rows=5></textarea><br><br>

    <label for="id_data_entrega">Data de Entrega:</label><br>
    <input type="date" id="id_data_entrega" name="data_entrega" required><br><br>

    <button type="submit">Criar Tarefa</button>
</form>

sources/templates/group-dropdown.html
<div class="group-dropdown">
    <label for="group-select">Selecionar Grupo:</label>
    <select id="group-select" onchange="updateGroup()">
        <option value="grupo1" {% if selected_group == 'grupo1' %}selected{% endif %}>Grupo 1</option>
        <option value="grupo2" {% if selected_group == 'grupo2' %}selected{% endif %}>Grupo 2</option>
    </select>
</div>

sources/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OpenShift Console</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'sidebar.html' %}

    <div class="main-content">
        <div class="content">
            {% include 'group-dropdown.html' %}

            {% if view == 'create' %}
            {% include 'create_group.html' %}
            {% elif view == 'createSubgroup' %}
            {% include 'create_subgroup.html' %}
            {% elif view == 'tasks' %}
            {% include 'all_task.html' %}
            {% elif view == 'criartasks' %}
            {% include 'criar_tarefa.html' %}
            {% elif view == 'subgroup' %}
            {% include 'subgroup.html' %}
            {% elif view == 'taskDetail' %}
            {% include 'task_detail_component.html' %}
            {% else %}
            {% include 'table_content.html' %}
            {% endif %}
   
        </div>
    </div>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

sources/templates/sidebar.html
<div class="sidebar">
    <div class="sidebar-header">
        <select id="user-role" onchange="updateRole()">
            <option value="Administrador">Administrador</option>
            <option value="Integrante">Integrante</option>
        </select>
    </div>
    <ul class="sidebar-menu">
        <a href="{% url 'dashboard' %}?view=create" class="admin-only"><li class="menu-item">Criar Grupo</li></a>
        <li class="menu-item submenu">
            Subgrupo
            <ul class="submenu-list">
                <a href="{% url 'dashboard' %}?view=createSubgroup">
                    <li class="submenu-item">Adicionar Subgrupo</li>
                </a>
                <a href="{% url 'dashboard' %}">
                    <li class="submenu-item">Todos os Subgrupos</li>
                </a>
            </ul>
        </li>
        <li class="menu-item submenu">
            Tarefas
            <ul class="submenu-list">
                <a href="{% url 'dashboard' %}?view=criartasks" class="admin-only">
                    <li class="submenu-item">Adicionar Tarefas</li>
                </a>
                <a href="{% url 'dashboard' %}?view=tasks">
                    <li class="submenu-item">Todas as Tarefas</li>
                </a>
            </ul>
        </li>
    </ul>
</div>

sources/templates/subgroup.html
<div class="subgroup-component">
    <h3>Integrantes do Subgrupo "{{ subgrupo.representante.nome }}"</h3>
    <table>
        <thead>
            <tr>
                <th>Nome</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for integrante in grupo.groups_data %}
            <tr>
                <td>{{ integrante.nome }}</td>
                <td>Associado ao Subgrupo</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Integrantes sem Subgrupo</h3>
    <table>
        <thead>
            <tr>
                <th>Nome</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for integrante in grupo.integrantes_sem_subgrupo %}
            <tr>
                <td>{{ integrante.nome }}</td>
                <td>Sem Subgrupo</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

sources/templates/table_content.html
<table>
    <thead>
        <tr>
            <th>Representante</th>
            <th>Integrantes</th>
            <th>Tarefas</th>
        </tr>
    </thead>
    <tbody>
        {% for group in grupo.groups_data %}
        <tr>
            
                <td><a href="{% url 'dashboard' %}?view=subgroup">{{ group.nome }}</a></td>
            
                <td>{{ group.integrantes|length }} / 10</td>
            <td>{{ group.tarefas }} / 10</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

sources/templates/task_detail_component.html
<div class="task-detail-content">
    <h2>Detalhes da Tarefa</h2>
    <p><strong>Descrição:</strong> {{ task.descricao }}</p>
    <p><strong>Data de Entrega:</strong> {{ task.data_entrega }}</p>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="file">Upload de Arquivo:</label>
        <input type="file" name="file" id="file">
        <button type="submit">Enviar</button>
    </form>
</div>